// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFoa7kdNvvWqAw3ZwEyqdFJhRl1cS8-qk',
    appId: '1:191831972910:web:efc43354dd54cc461ed3bf',
    messagingSenderId: '191831972910',
    projectId: 'trucky-69',
    authDomain: 'trucky-69.firebaseapp.com',
    storageBucket: 'trucky-69.appspot.com',
    measurementId: 'G-E6GRBPT5MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDje3HqjIg8UDFQFI4bFtF6Vb0wHnz9JT8',
    appId: '1:191831972910:android:898dadacd5020cb41ed3bf',
    messagingSenderId: '191831972910',
    projectId: 'trucky-69',
    storageBucket: 'trucky-69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVTn5N8vfB3wVWpXxQ4zf77qx4xBv1CJk',
    appId: '1:191831972910:ios:598949789af13a961ed3bf',
    messagingSenderId: '191831972910',
    projectId: 'trucky-69',
    storageBucket: 'trucky-69.appspot.com',
    iosBundleId: 'com.example.trucky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVTn5N8vfB3wVWpXxQ4zf77qx4xBv1CJk',
    appId: '1:191831972910:ios:598949789af13a961ed3bf',
    messagingSenderId: '191831972910',
    projectId: 'trucky-69',
    storageBucket: 'trucky-69.appspot.com',
    iosBundleId: 'com.example.trucky',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFoa7kdNvvWqAw3ZwEyqdFJhRl1cS8-qk',
    appId: '1:191831972910:web:06051406b19bafaa1ed3bf',
    messagingSenderId: '191831972910',
    projectId: 'trucky-69',
    authDomain: 'trucky-69.firebaseapp.com',
    storageBucket: 'trucky-69.appspot.com',
    measurementId: 'G-0BP017JZSX',
  );
}
